openapi: 3.0.3
info:
  title: Calendar Web Application API
  version: 1.0.0
  description: REST API for calendar management with user authentication and sharing

servers:
  - url: http://localhost:3000/api
    description: Development server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        name:
          type: string
        timezone:
          type: string
          default: UTC

    Calendar:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        color:
          type: string
          default: '#3788d8'
        description:
          type: string

    Event:
      type: object
      properties:
        id:
          type: string
          format: uuid
        calendar_id:
          type: string
          format: uuid
        title:
          type: string
        start_datetime:
          type: string
          format: date-time
        end_datetime:
          type: string
          format: date-time
        description:
          type: string
        recurrence_rule:
          type: string

    Permission:
      type: object
      properties:
        calendar_id:
          type: string
          format: uuid
        user_id:
          type: string
          format: uuid
        permission_level:
          type: string
          enum: [view, edit, admin]

    Error:
      type: object
      properties:
        error:
          type: string
        message:
          type: string

paths:
  /auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - name
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  minLength: 8
                name:
                  type: string
                timezone:
                  type: string
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /auth/login:
    post:
      summary: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  user:
                    $ref: '#/components/schemas/User'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /calendars:
    get:
      summary: Get user's calendars
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of user's calendars
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Calendar'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      summary: Create a new calendar
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                color:
                  type: string
                description:
                  type: string
      responses:
        '201':
          description: Calendar created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Calendar'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /calendars/{calendarId}:
    parameters:
      - name: calendarId
        in: path
        required: true
        schema:
          type: string
          format: uuid

    get:
      summary: Get calendar details
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Calendar details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Calendar'
        '403':
          description: Forbidden
        '404':
          description: Calendar not found

    put:
      summary: Update calendar
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                color:
                  type: string
                description:
                  type: string
      responses:
        '200':
          description: Calendar updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Calendar'
        '403':
          description: Forbidden

    delete:
      summary: Delete calendar
      security:
        - bearerAuth: []
      responses:
        '204':
          description: Calendar deleted
        '403':
          description: Forbidden

  /calendars/{calendarId}/share:
    post:
      summary: Share calendar with user
      security:
        - bearerAuth: []
      parameters:
        - name: calendarId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - user_email
                - permission_level
              properties:
                user_email:
                  type: string
                  format: email
                permission_level:
                  type: string
                  enum: [view, edit, admin]
      responses:
        '200':
          description: Calendar shared successfully
        '400':
          description: Invalid input
        '403':
          description: Forbidden

  /calendars/{calendarId}/events:
    get:
      summary: Get calendar events
      security:
        - bearerAuth: []
      parameters:
        - name: calendarId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: start
          in: query
          schema:
            type: string
            format: date-time
        - name: end
          in: query
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: List of events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
        '403':
          description: Forbidden

    post:
      summary: Create event
      security:
        - bearerAuth: []
      parameters:
        - name: calendarId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - start_datetime
                - end_datetime
              properties:
                title:
                  type: string
                start_datetime:
                  type: string
                  format: date-time
                end_datetime:
                  type: string
                  format: date-time
                description:
                  type: string
                recurrence_rule:
                  type: string
      responses:
        '201':
          description: Event created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '400':
          description: Invalid input
        '403':
          description: Forbidden

  /events/{eventId}:
    parameters:
      - name: eventId
        in: path
        required: true
        schema:
          type: string
          format: uuid

    get:
      summary: Get event details
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Event details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '403':
          description: Forbidden
        '404':
          description: Event not found

    put:
      summary: Update event
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                start_datetime:
                  type: string
                  format: date-time
                end_datetime:
                  type: string
                  format: date-time
                description:
                  type: string
                recurrence_rule:
                  type: string
      responses:
        '200':
          description: Event updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '403':
          description: Forbidden

    delete:
      summary: Delete event
      security:
        - bearerAuth: []
      responses:
        '204':
          description: Event deleted
        '403':
          description: Forbidden